#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Sphinx configuration for the KanbanMF documentation.

Builds the narrative documentation (the Markdown files at the repository
root, pulled in via MyST) plus a complete API reference generated from the
backend source with ``autodoc``/``autosummary``.

Build locally with::

    source .venv/bin/activate
    pip3 install -r backend/requirements.txt
    cd docs && make html

For the full list of built-in configuration values, see
https://www.sphinx-doc.org/en/master/usage/configuration.html
"""

import os
import sys
from datetime import date
from pathlib import Path

# -- Path setup --------------------------------------------------------------
# conf.py -> docs/source/ -> docs/ -> <repo root>
_REPO_ROOT = Path(__file__).parent.parent.parent
_BACKEND = _REPO_ROOT / "backend"

# The backend is imported as the top-level ``src`` namespace package
# (``from src.model.board import Board``), so ``backend/`` — not
# ``backend/src/`` — is what has to be on sys.path.
sys.path.insert(0, str(_BACKEND))

# autodoc imports every module it documents, and importing anything under
# ``src`` instantiates ``src.core.config.Settings`` (and fastapi-mail's
# ConnectionConfig) at module level. Those need a handful of settings that
# have no default, and a docs build must not depend on a real backend/.env.
# Environment variables take precedence over the .env file in
# pydantic-settings, so these placeholders keep the build hermetic and free
# of real credentials. Nothing here ever opens a connection.
os.environ.setdefault(
    "DATABASE_URL", "postgresql+psycopg://docs:docs@localhost:5432/docs"
)
os.environ.setdefault("SECRET_KEY", "documentation-build-only")
os.environ.setdefault("SMTP_HOST", "localhost")
os.environ.setdefault("SMTP_PORT", "25")
os.environ.setdefault("SMTP_FROM_EMAIL", "docs@example.com")
os.environ.setdefault("SMTP_FROM_NAME", "KanbanMF docs")

# -- Project information -----------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#project-information

project = "Kanban MF"
copyright = f"{date.today().year}, Jaume Figueras"
author = "Jaume Figueras"
release = "0.1"
version = "0.1"

# -- General configuration ---------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#general-configuration

extensions = [
    "sphinx.ext.autodoc",       # pull docstrings out of the backend source
    "sphinx.ext.autosummary",   # generate one page per module, recursively
    "sphinx.ext.napoleon",      # Google/NumPy style docstrings
    "sphinx.ext.viewcode",      # "[source]" links next to every object
    "sphinx.ext.intersphinx",   # cross-link to Python/SQLAlchemy/Pydantic docs
    "sphinx.ext.todo",          # .. todo:: directives, rendered (see below)
    "sphinx.ext.coverage",      # `make coverage` reports undocumented objects
    "myst_parser",              # so the root README.md & friends can be included
]

templates_path = ["_templates"]
exclude_patterns = []

# Warn about broken cross-references; combine with `make html SPHINXOPTS=-W`
# in CI to make them fatal.
nitpicky = False

# MyST is configured so the root Markdown files (README.md, SETUP.md,
# PENDING.md) can be {include}d rather than duplicated. They link to sibling
# repo files (LICENSE, deploy/apache-kanbanmf.conf) that are not documentation
# pages: those links are correct on GitHub, where the files are read from, but
# MyST can't resolve them to a doc. Don't warn about it. Make them absolute
# https://github.com/... URLs in the source files if you want them to work from
# the rendered HTML too.
suppress_warnings = ["myst.xref_missing"]

# -- Autodoc / autosummary ---------------------------------------------------

autosummary_generate = True
autosummary_imported_members = False

autodoc_default_options = {
    "members": True,
    "undoc-members": True,
    "show-inheritance": True,
    "member-order": "bysource",
    # src/model/__init__.py re-exports every model through __all__, which
    # autodoc would otherwise honour — documenting e.g. User both as
    # src.model.User and src.model.user.User and making every cross-reference
    # to it ambiguous. Ignoring __all__ documents each object only where it is
    # actually defined.
    "ignore-module-all": True,
}
# Keep signatures readable: don't expand type aliases or evaluate defaults.
autodoc_typehints = "signature"
autodoc_preserve_defaults = True
# SQLAlchemy models get an autogenerated __init__ signature that says nothing.
autoclass_content = "class"
autodoc_class_signature = "mixed"
# Anything that can't be imported at build time (none today) goes here rather
# than breaking the build.
autodoc_mock_imports = []

# -- Napoleon ----------------------------------------------------------------

napoleon_google_docstring = True
napoleon_numpy_docstring = True
napoleon_include_init_with_doc = True
napoleon_include_private_with_doc = False
napoleon_use_admonition_for_examples = True
napoleon_use_admonition_for_notes = True
napoleon_use_rtype = True

# -- Intersphinx -------------------------------------------------------------
# Fetched over the network; a short timeout means an offline build degrades to
# a warning instead of hanging.

intersphinx_mapping = {
    "python": ("https://docs.python.org/3", None),
    "sqlalchemy": ("https://docs.sqlalchemy.org/en/20/", None),
    "pydantic": ("https://docs.pydantic.dev/latest/", None),
    "alembic": ("https://alembic.sqlalchemy.org/en/latest/", None),
}
intersphinx_timeout = 5

# -- MyST (Markdown) ---------------------------------------------------------

myst_enable_extensions = [
    "colon_fence",
    "deflist",
    "fieldlist",
    "linkify",
    "substitution",
    "tasklist",
]
myst_heading_anchors = 3

source_suffix = {
    ".rst": "restructuredtext",
    ".md": "markdown",
}

# -- Todo --------------------------------------------------------------------

todo_include_todos = True

# -- Options for HTML output -------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-html-output

html_theme = "sphinx_rtd_theme"
html_static_path = ["_static"]
html_css_files = ["custom.css"]
html_title = f"{project} {release}"

html_theme_options = {
    "logo_only": False,
    "prev_next_buttons_location": "bottom",
    "style_external_links": True,
    "collapse_navigation": False,
    "sticky_navigation": True,
    "navigation_depth": 4,
    "includehidden": True,
    "titles_only": False,
}

html_show_sourcelink = True
