"""add time entries

Revision ID: 57558eec81f6
Revises: d8c0ac70cbf7
Create Date: 2026-09-01 19:47:57.698311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '57558eec81f6'
down_revision: Union[str, Sequence[str], None] = 'd8c0ac70cbf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # A time entry is a snapshot: it copies the board name, card name and
    # labels instead of referencing them, so renaming, relabelling, archiving
    # or deleting a card leaves the record of the time already spent intact.
    # Hence no FK here other than the owning user.
    op.create_table('time_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Owner of the entry. Time tracking is private: entries are never shared.'),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True, comment='NULL while the entry is still running.'),
    sa.Column('board_name', sa.String(length=255), nullable=False, comment="Copy of the board's name when the entry was created."),
    sa.Column('card_name', sa.String(length=255), nullable=False, comment="Copy of the card's name when the entry was created."),
    sa.Column('labels', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False, comment="Copy of the card's labels when the entry was created: [{name, color}, ...]."),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('ended_at IS NULL OR ended_at > started_at', name='ck_time_entries_end_after_start'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_time_entries_id'), 'time_entries', ['id'], unique=False)
    op.create_index(op.f('ix_time_entries_user_id'), 'time_entries', ['user_id'], unique=False)
    # Partial unique index: an entry with no ended_at is the running one, and
    # a user can only have one of those at a time. Enforced here so a double
    # "Start" can't slip through between the API's check and its insert.
    op.create_index('ux_time_entries_one_running_per_user', 'time_entries', ['user_id'], unique=True, postgresql_where=sa.text('ended_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ux_time_entries_one_running_per_user', table_name='time_entries', postgresql_where=sa.text('ended_at IS NULL'))
    op.drop_index(op.f('ix_time_entries_user_id'), table_name='time_entries')
    op.drop_index(op.f('ix_time_entries_id'), table_name='time_entries')
    op.drop_table('time_entries')
    # ### end Alembic commands ###
