"""backfill column comments

The dev DB was originally bootstrapped from a raw SQL dump (src/model/sql/)
predating the descriptive `comment=` values now on several model columns, so
its actual COMMENT ON COLUMN metadata had drifted from the models. This
migration is comment-only — no type, nullability, or default changes.

Revision ID: 5a9d142c1cef
Revises: b432680216a0
Create Date: 2026-07-08 21:02:16.524163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5a9d142c1cef'
down_revision: Union[str, Sequence[str], None] = 'b432680216a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('board_notification_offsets', 'offset_days',
               existing_type=sa.SMALLINT(),
               comment='Days relative to due_at: negative=before, 0=on due day, positive=after.',
               existing_nullable=False)
    op.alter_column('board_notification_settings', 'board_id',
               existing_type=sa.UUID(),
               comment='One-to-one with Board. Deleting the board also deletes its notification settings.',
               existing_nullable=False)
    op.alter_column('board_notification_settings', 'notify_hour',
               existing_type=sa.SMALLINT(),
               comment="Hour of day (0-23) at which notifications are sent, in each recipient's own timezone.",
               existing_nullable=False,
               existing_server_default=sa.text("'9'::smallint"))
    op.alter_column('board_notification_settings', 'overdue_repeat_after_days',
               existing_type=sa.SMALLINT(),
               comment='Once a card is this many days past due, notify daily until resolved. NULL disables the repeat.',
               existing_nullable=True)
    op.alter_column('board_shares', 'shared_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='When the board was shared with this user.',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('boards', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               comment='Soft-delete flag. Deleted boards are hidden but retained in the DB.',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('card_assignees', 'assigned_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='When the user was assigned to this card.',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('card_due_notifications', 'notification_date',
               existing_type=sa.DATE(),
               comment="Calendar day (in the recipient's timezone) this notification was sent for.",
               existing_nullable=False)
    op.alter_column('card_members', 'added_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='When the user was added as a member of this card.',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('checklist_items', 'position',
               existing_type=sa.INTEGER(),
               comment='Display order within the checklist. Lower value = higher position.',
               existing_nullable=False)
    op.alter_column('checklists', 'position',
               existing_type=sa.INTEGER(),
               comment="Display order among the card's checklists. Lower value = higher position.",
               existing_nullable=False)
    op.alter_column('labels', 'color',
               existing_type=sa.VARCHAR(length=50),
               comment='Hex colour code (e.g. #FF5733) or any CSS colour string.',
               existing_nullable=False)
    op.alter_column('ui_board_colors', 'color',
               existing_type=sa.VARCHAR(length=50),
               comment='Hex colour code (e.g. #FF5733) or any CSS colour string.',
               existing_nullable=False)
    op.alter_column('ui_card_colors', 'color',
               existing_type=sa.VARCHAR(length=50),
               comment='Hex colour code (e.g. #FF5733) or any CSS colour string.',
               existing_nullable=False)
    op.alter_column('ui_list_colors', 'color',
               existing_type=sa.VARCHAR(length=50),
               comment='Hex colour code (e.g. #FF5733) or any CSS colour string.',
               existing_nullable=False)
    op.alter_column('user_avatars', 'user_id',
               existing_type=sa.UUID(),
               comment='One-to-one with User. Deleting the user also deletes the avatar.',
               existing_nullable=False)
    op.alter_column('user_avatars', 'data',
               existing_type=postgresql.BYTEA(),
               comment='Raw image bytes. Maximum 100 KB.',
               existing_nullable=False)
    op.alter_column('user_avatars', 'mime_type',
               existing_type=sa.VARCHAR(length=32),
               comment='e.g. image/jpeg, image/png, image/webp, image/gif',
               existing_nullable=False)
    op.alter_column('user_board_stars', 'starred_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='When the user starred this board.',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_identities', 'provider_user_id',
               existing_type=sa.VARCHAR(length=255),
               comment="Google's unique user ID ('sub' field in the ID token).",
               existing_nullable=True)
    op.alter_column('user_identities', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               comment='bcrypt hashed password. Only set for local accounts.',
               existing_nullable=True)
    op.alter_column('user_identities', 'verification_token',
               existing_type=sa.VARCHAR(length=255),
               comment='One-time token sent by email. Cleared after successful verification.',
               existing_nullable=True)
    op.alter_column('user_preferences', 'user_id',
               existing_type=sa.UUID(),
               comment='One-to-one with User. Deleting the user also deletes the avatar.',
               existing_nullable=False)
    op.alter_column('user_preferences', 'initials',
               existing_type=sa.VARCHAR(length=3),
               comment='Up to 3 custom initials. NULL means use the computed default (first letter of each display_name word).',
               existing_nullable=True)
    op.alter_column('user_preferences', 'date_format',
               existing_type=postgresql.ENUM('numeric', 'textual', name='dateformat'),
               comment="How dates are displayed on cards: 'numeric' (27/06/2026) or 'textual' (27 June 2026).",
               existing_nullable=False,
               existing_server_default=sa.text("'numeric'::dateformat"))
    op.alter_column('user_preferences', 'timezone',
               existing_type=sa.VARCHAR(length=50),
               comment="IANA timezone name (e.g. 'Europe/Madrid'). Used to localize due-date notification hours for this user.",
               existing_nullable=False,
               existing_server_default=sa.text("'UTC'::character varying"))
    op.alter_column('user_sessions', 'hashed_refresh_token',
               existing_type=sa.VARCHAR(length=255),
               comment='bcrypt hash of the refresh token. Plain token is sent via HTTP-only cookie.',
               existing_nullable=False)
    op.alter_column('user_sessions', 'device_info',
               existing_type=sa.VARCHAR(length=255),
               comment="e.g. 'Chrome on Windows 11' or 'Safari on iPhone'. Informational only.",
               existing_nullable=True)
    op.alter_column('user_sessions', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Session expiry. Refresh tokens last 30 days.',
               existing_nullable=False)
    op.alter_column('user_sessions', 'last_used_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Updated every time the refresh token is used to get a new access token.',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment='Unique identifier. Changeable for local accounts; managed by Google for OAuth users.',
               existing_nullable=False)
    op.alter_column('users', 'is_verified',
               existing_type=sa.BOOLEAN(),
               comment='True when email has been verified. Always True for Google users. Resets to False when local user changes email.',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_verified',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='True when email has been verified. Always True for Google users. Resets to False when local user changes email.',
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Unique identifier. Changeable for local accounts; managed by Google for OAuth users.',
               existing_nullable=False)
    op.alter_column('user_sessions', 'last_used_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Updated every time the refresh token is used to get a new access token.',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_sessions', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Session expiry. Refresh tokens last 30 days.',
               existing_nullable=False)
    op.alter_column('user_sessions', 'device_info',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment="e.g. 'Chrome on Windows 11' or 'Safari on iPhone'. Informational only.",
               existing_nullable=True)
    op.alter_column('user_sessions', 'hashed_refresh_token',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='bcrypt hash of the refresh token. Plain token is sent via HTTP-only cookie.',
               existing_nullable=False)
    op.alter_column('user_preferences', 'timezone',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment="IANA timezone name (e.g. 'Europe/Madrid'). Used to localize due-date notification hours for this user.",
               existing_nullable=False,
               existing_server_default=sa.text("'UTC'::character varying"))
    op.alter_column('user_preferences', 'date_format',
               existing_type=postgresql.ENUM('numeric', 'textual', name='dateformat'),
               comment=None,
               existing_comment="How dates are displayed on cards: 'numeric' (27/06/2026) or 'textual' (27 June 2026).",
               existing_nullable=False,
               existing_server_default=sa.text("'numeric'::dateformat"))
    op.alter_column('user_preferences', 'initials',
               existing_type=sa.VARCHAR(length=3),
               comment=None,
               existing_comment='Up to 3 custom initials. NULL means use the computed default (first letter of each display_name word).',
               existing_nullable=True)
    op.alter_column('user_preferences', 'user_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='One-to-one with User. Deleting the user also deletes the avatar.',
               existing_nullable=False)
    op.alter_column('user_identities', 'verification_token',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='One-time token sent by email. Cleared after successful verification.',
               existing_nullable=True)
    op.alter_column('user_identities', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='bcrypt hashed password. Only set for local accounts.',
               existing_nullable=True)
    op.alter_column('user_identities', 'provider_user_id',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment="Google's unique user ID ('sub' field in the ID token).",
               existing_nullable=True)
    op.alter_column('user_board_stars', 'starred_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='When the user starred this board.',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_avatars', 'mime_type',
               existing_type=sa.VARCHAR(length=32),
               comment=None,
               existing_comment='e.g. image/jpeg, image/png, image/webp, image/gif',
               existing_nullable=False)
    op.alter_column('user_avatars', 'data',
               existing_type=postgresql.BYTEA(),
               comment=None,
               existing_comment='Raw image bytes. Maximum 100 KB.',
               existing_nullable=False)
    op.alter_column('user_avatars', 'user_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='One-to-one with User. Deleting the user also deletes the avatar.',
               existing_nullable=False)
    op.alter_column('ui_list_colors', 'color',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Hex colour code (e.g. #FF5733) or any CSS colour string.',
               existing_nullable=False)
    op.alter_column('ui_card_colors', 'color',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Hex colour code (e.g. #FF5733) or any CSS colour string.',
               existing_nullable=False)
    op.alter_column('ui_board_colors', 'color',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Hex colour code (e.g. #FF5733) or any CSS colour string.',
               existing_nullable=False)
    op.alter_column('labels', 'color',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Hex colour code (e.g. #FF5733) or any CSS colour string.',
               existing_nullable=False)
    op.alter_column('checklists', 'position',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment="Display order among the card's checklists. Lower value = higher position.",
               existing_nullable=False)
    op.alter_column('checklist_items', 'position',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Display order within the checklist. Lower value = higher position.',
               existing_nullable=False)
    op.alter_column('card_members', 'added_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='When the user was added as a member of this card.',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('card_due_notifications', 'notification_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment="Calendar day (in the recipient's timezone) this notification was sent for.",
               existing_nullable=False)
    op.alter_column('card_assignees', 'assigned_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='When the user was assigned to this card.',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('boards', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Soft-delete flag. Deleted boards are hidden but retained in the DB.',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('board_shares', 'shared_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='When the board was shared with this user.',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('board_notification_settings', 'overdue_repeat_after_days',
               existing_type=sa.SMALLINT(),
               comment=None,
               existing_comment='Once a card is this many days past due, notify daily until resolved. NULL disables the repeat.',
               existing_nullable=True)
    op.alter_column('board_notification_settings', 'notify_hour',
               existing_type=sa.SMALLINT(),
               comment=None,
               existing_comment="Hour of day (0-23) at which notifications are sent, in each recipient's own timezone.",
               existing_nullable=False,
               existing_server_default=sa.text("'9'::smallint"))
    op.alter_column('board_notification_settings', 'board_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='One-to-one with Board. Deleting the board also deletes its notification settings.',
               existing_nullable=False)
    op.alter_column('board_notification_offsets', 'offset_days',
               existing_type=sa.SMALLINT(),
               comment=None,
               existing_comment='Days relative to due_at: negative=before, 0=on due day, positive=after.',
               existing_nullable=False)
    # ### end Alembic commands ###
