"""per-user board notification settings

Revision ID: 5d8278735dc3
Revises: 5a9d142c1cef
Create Date: 2026-07-08 22:31:08.953731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d8278735dc3'
down_revision: Union[str, Sequence[str], None] = '5a9d142c1cef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Add user_id as nullable first — can't be NOT NULL until backfilled.
    op.add_column("board_notification_settings", sa.Column("user_id", sa.UUID(), nullable=True))
    op.add_column("board_notification_offsets", sa.Column("user_id", sa.UUID(), nullable=True))
    # 2. Backfill: existing board-wide settings become the board owner's
    # personal settings — the closest equivalent of "who had this enabled".
    op.execute("UPDATE board_notification_settings s SET user_id = b.owner_id FROM boards b WHERE b.id = s.board_id")
    op.execute("UPDATE board_notification_offsets o SET user_id = s.user_id FROM board_notification_settings s WHERE s.board_id = o.board_id")
    # 3. Now safe to enforce NOT NULL.
    op.alter_column("board_notification_settings", "user_id", nullable=False)
    op.alter_column("board_notification_offsets", "user_id", nullable=False)
    # 4. Fix board_notification_offsets' FK + PK BEFORE changing settings' PK
    # (the old FK references settings.board_id alone — drop it first).
    op.drop_constraint("board_notification_offsets_board_id_fkey", "board_notification_offsets", type_="foreignkey")
    op.drop_constraint("board_notification_offsets_pkey", "board_notification_offsets", type_="primary")
    op.create_primary_key("board_notification_offsets_pkey", "board_notification_offsets",
                          ["board_id", "user_id", "offset_days"])
    # 5. Now change board_notification_settings' PK to (board_id, user_id).
    op.drop_constraint("board_notification_settings_pkey", "board_notification_settings", type_="primary")
    op.create_primary_key("board_notification_settings_pkey", "board_notification_settings", ["board_id", "user_id"])
    op.create_foreign_key(
        "board_notification_settings_user_id_fkey", "board_notification_settings",
        "users", ["user_id"], ["id"], ondelete="CASCADE",
    )
    # 6. Re-add offsets' FK, now composite, pointing at the new composite PK.
    op.create_foreign_key(
        "board_notification_offsets_board_id_fkey", "board_notification_offsets",
        "board_notification_settings", ["board_id", "user_id"], ["board_id", "user_id"], ondelete="CASCADE",
    )
    op.create_foreign_key(
        "board_notification_offsets_user_id_fkey", "board_notification_offsets",
        "users", ["user_id"], ["id"], ondelete="CASCADE",
    )


def downgrade() -> None:
    """Downgrade schema."""
    raise NotImplementedError("Per-user notification settings can't be safely collapsed back to per-board.")
