"""initial schema

Revision ID: b432680216a0
Revises: 
Create Date: 2026-07-08 20:57:40.205084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b432680216a0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False, comment='Unique identifier. Changeable for local accounts; managed by Google for OAuth users.'),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False, comment='True when email has been verified. Always True for Google users. Resets to False when local user changes email.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('boards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False, comment='Soft-delete flag. Deleted boards are hidden but retained in the DB.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_boards_id'), 'boards', ['id'], unique=False)
    op.create_index(op.f('ix_boards_owner_id'), 'boards', ['owner_id'], unique=False)
    op.create_table('ui_board_orders',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('starred_ids', postgresql.ARRAY(sa.UUID()), server_default='{}', nullable=False),
    sa.Column('owned_ids', postgresql.ARRAY(sa.UUID()), server_default='{}', nullable=False),
    sa.Column('shared_ids', postgresql.ARRAY(sa.UUID()), server_default='{}', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('user_avatars',
    sa.Column('user_id', sa.UUID(), nullable=False, comment='One-to-one with User. Deleting the user also deletes the avatar.'),
    sa.Column('data', sa.LargeBinary(), nullable=False, comment='Raw image bytes. Maximum 100 KB.'),
    sa.Column('mime_type', sa.String(length=32), nullable=False, comment='e.g. image/jpeg, image/png, image/webp, image/gif'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('octet_length(data) <= 102400', name='ck_avatar_max_size'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('user_identities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.Enum('local', 'google', name='authprovider'), nullable=False),
    sa.Column('provider_user_id', sa.String(length=255), nullable=True, comment="Google's unique user ID ('sub' field in the ID token)."),
    sa.Column('access_token', sa.String(length=2048), nullable=True),
    sa.Column('refresh_token', sa.String(length=2048), nullable=True),
    sa.Column('token_expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=True, comment='bcrypt hashed password. Only set for local accounts.'),
    sa.Column('verification_token', sa.String(length=255), nullable=True, comment='One-time token sent by email. Cleared after successful verification.'),
    sa.Column('verification_token_expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_identities_user_id'), 'user_identities', ['user_id'], unique=False)
    op.create_table('user_preferences',
    sa.Column('user_id', sa.UUID(), nullable=False, comment='One-to-one with User. Deleting the user also deletes the avatar.'),
    sa.Column('language_locale', sa.String(length=10), nullable=False),
    sa.Column('number_locale', sa.String(length=10), nullable=False),
    sa.Column('initials', sa.String(length=3), nullable=True, comment='Up to 3 custom initials. NULL means use the computed default (first letter of each display_name word).'),
    sa.Column('date_format', sa.Enum('numeric', 'textual', name='dateformat'), server_default='numeric', nullable=False, comment="How dates are displayed on cards: 'numeric' (27/06/2026) or 'textual' (27 June 2026)."),
    sa.Column('timezone', sa.String(length=50), server_default='UTC', nullable=False, comment="IANA timezone name (e.g. 'Europe/Madrid'). Used to localize due-date notification hours for this user."),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('user_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('hashed_refresh_token', sa.String(length=255), nullable=False, comment='bcrypt hash of the refresh token. Plain token is sent via HTTP-only cookie.'),
    sa.Column('device_info', sa.String(length=255), nullable=True, comment="e.g. 'Chrome on Windows 11' or 'Safari on iPhone'. Informational only."),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False, comment='Session expiry. Refresh tokens last 30 days.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Updated every time the refresh token is used to get a new access token.'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.create_table('board_lists',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('board_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_board_lists_board_id'), 'board_lists', ['board_id'], unique=False)
    op.create_index(op.f('ix_board_lists_id'), 'board_lists', ['id'], unique=False)
    op.create_table('board_notification_settings',
    sa.Column('board_id', sa.UUID(), nullable=False, comment='One-to-one with Board. Deleting the board also deletes its notification settings.'),
    sa.Column('is_enabled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('notify_hour', sa.SmallInteger(), server_default='9', nullable=False, comment="Hour of day (0-23) at which notifications are sent, in each recipient's own timezone."),
    sa.Column('overdue_repeat_after_days', sa.SmallInteger(), nullable=True, comment='Once a card is this many days past due, notify daily until resolved. NULL disables the repeat.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('notify_hour >= 0 AND notify_hour <= 23', name='ck_board_notification_settings_notify_hour_range'),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('board_id')
    )
    op.create_table('board_shares',
    sa.Column('board_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('shared_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='When the board was shared with this user.'),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('board_id', 'user_id')
    )
    op.create_table('labels',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('board_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=50), nullable=False, comment='Hex colour code (e.g. #FF5733) or any CSS colour string.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_labels_board_id'), 'labels', ['board_id'], unique=False)
    op.create_index(op.f('ix_labels_id'), 'labels', ['id'], unique=False)
    op.create_table('ui_board_colors',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('board_id', sa.UUID(), nullable=False),
    sa.Column('color', sa.String(length=50), nullable=False, comment='Hex colour code (e.g. #FF5733) or any CSS colour string.'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'board_id')
    )
    op.create_table('ui_board_list_orders',
    sa.Column('board_id', sa.UUID(), nullable=False),
    sa.Column('list_ids', postgresql.ARRAY(sa.UUID()), server_default='{}', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('board_id')
    )
    op.create_table('user_board_stars',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('board_id', sa.UUID(), nullable=False),
    sa.Column('starred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='When the user starred this board.'),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'board_id')
    )
    op.create_table('board_notification_offsets',
    sa.Column('board_id', sa.UUID(), nullable=False),
    sa.Column('offset_days', sa.SmallInteger(), nullable=False, comment='Days relative to due_at: negative=before, 0=on due day, positive=after.'),
    sa.ForeignKeyConstraint(['board_id'], ['board_notification_settings.board_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('board_id', 'offset_days')
    )
    op.create_table('cards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('list_id', sa.UUID(), nullable=False),
    sa.Column('creator_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['list_id'], ['board_lists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cards_creator_id'), 'cards', ['creator_id'], unique=False)
    op.create_index(op.f('ix_cards_id'), 'cards', ['id'], unique=False)
    op.create_index(op.f('ix_cards_list_id'), 'cards', ['list_id'], unique=False)
    op.create_table('ui_list_card_orders',
    sa.Column('list_id', sa.UUID(), nullable=False),
    sa.Column('card_ids', postgresql.ARRAY(sa.UUID()), server_default='{}', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['list_id'], ['board_lists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('list_id')
    )
    op.create_table('ui_list_colors',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('list_id', sa.UUID(), nullable=False),
    sa.Column('color', sa.String(length=50), nullable=False, comment='Hex colour code (e.g. #FF5733) or any CSS colour string.'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['list_id'], ['board_lists.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'list_id')
    )
    op.create_table('card_assignees',
    sa.Column('card_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='When the user was assigned to this card.'),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('card_id', 'user_id')
    )
    op.create_table('card_due_notifications',
    sa.Column('card_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('notification_date', sa.Date(), nullable=False, comment="Calendar day (in the recipient's timezone) this notification was sent for."),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('card_id', 'user_id', 'notification_date')
    )
    op.create_table('card_labels',
    sa.Column('card_id', sa.UUID(), nullable=False),
    sa.Column('label_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['label_id'], ['labels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('card_id', 'label_id')
    )
    op.create_table('card_members',
    sa.Column('card_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='When the user was added as a member of this card.'),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('card_id', 'user_id')
    )
    op.create_table('checklists',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('card_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False, comment="Display order among the card's checklists. Lower value = higher position."),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checklists_card_id'), 'checklists', ['card_id'], unique=False)
    op.create_index(op.f('ix_checklists_id'), 'checklists', ['id'], unique=False)
    op.create_table('ui_card_colors',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('card_id', sa.UUID(), nullable=False),
    sa.Column('color', sa.String(length=50), nullable=False, comment='Hex colour code (e.g. #FF5733) or any CSS colour string.'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'card_id')
    )
    op.create_table('checklist_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('checklist_id', sa.UUID(), nullable=False),
    sa.Column('text', sa.String(length=500), nullable=False),
    sa.Column('is_done', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('position', sa.Integer(), nullable=False, comment='Display order within the checklist. Lower value = higher position.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['checklist_id'], ['checklists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checklist_items_checklist_id'), 'checklist_items', ['checklist_id'], unique=False)
    op.create_index(op.f('ix_checklist_items_id'), 'checklist_items', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_checklist_items_id'), table_name='checklist_items')
    op.drop_index(op.f('ix_checklist_items_checklist_id'), table_name='checklist_items')
    op.drop_table('checklist_items')
    op.drop_table('ui_card_colors')
    op.drop_index(op.f('ix_checklists_id'), table_name='checklists')
    op.drop_index(op.f('ix_checklists_card_id'), table_name='checklists')
    op.drop_table('checklists')
    op.drop_table('card_members')
    op.drop_table('card_labels')
    op.drop_table('card_due_notifications')
    op.drop_table('card_assignees')
    op.drop_table('ui_list_colors')
    op.drop_table('ui_list_card_orders')
    op.drop_index(op.f('ix_cards_list_id'), table_name='cards')
    op.drop_index(op.f('ix_cards_id'), table_name='cards')
    op.drop_index(op.f('ix_cards_creator_id'), table_name='cards')
    op.drop_table('cards')
    op.drop_table('board_notification_offsets')
    op.drop_table('user_board_stars')
    op.drop_table('ui_board_list_orders')
    op.drop_table('ui_board_colors')
    op.drop_index(op.f('ix_labels_id'), table_name='labels')
    op.drop_index(op.f('ix_labels_board_id'), table_name='labels')
    op.drop_table('labels')
    op.drop_table('board_shares')
    op.drop_table('board_notification_settings')
    op.drop_index(op.f('ix_board_lists_id'), table_name='board_lists')
    op.drop_index(op.f('ix_board_lists_board_id'), table_name='board_lists')
    op.drop_table('board_lists')
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_table('user_preferences')
    op.drop_index(op.f('ix_user_identities_user_id'), table_name='user_identities')
    op.drop_table('user_identities')
    op.drop_table('user_avatars')
    op.drop_table('ui_board_orders')
    op.drop_index(op.f('ix_boards_owner_id'), table_name='boards')
    op.drop_index(op.f('ix_boards_id'), table_name='boards')
    op.drop_table('boards')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
