"""add position to labels

Revision ID: d8c0ac70cbf7
Revises: f14656ed6e8c
Create Date: 2026-07-16 14:19:44.462826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8c0ac70cbf7'
down_revision: Union[str, Sequence[str], None] = 'f14656ed6e8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Added nullable first — existing rows need a backfilled position before
    # the NOT NULL constraint can be applied (autogenerate's plain add_column
    # would fail on any board that already has labels).
    op.add_column(
        'labels',
        sa.Column(
            'position',
            sa.Integer(),
            nullable=True,
            comment="Display order among the board's labels. Lower value = higher position.",
        ),
    )
    # Backfill: preserve each board's existing label order (by creation time)
    # as the initial position, so labels don't visibly reshuffle on upgrade.
    op.execute(
        """
        UPDATE labels
        SET position = sub.rn
        FROM (
            SELECT id, ROW_NUMBER() OVER (PARTITION BY board_id ORDER BY created_at, id) - 1 AS rn
            FROM labels
        ) AS sub
        WHERE labels.id = sub.id
        """
    )
    op.alter_column('labels', 'position', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('labels', 'position')
    # ### end Alembic commands ###
