"""drop redundant offset user fk

Revision ID: f14656ed6e8c
Revises: 5d8278735dc3
Create Date: 2026-07-08 22:51:56.501554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f14656ed6e8c'
down_revision: Union[str, Sequence[str], None] = '5d8278735dc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('board_notification_offsets_user_id_fkey'), 'board_notification_offsets', type_='foreignkey')
    op.alter_column('board_notification_settings', 'board_id',
               existing_type=sa.UUID(),
               comment="Deleting the board also deletes every user's notification settings for it.",
               existing_comment='One-to-one with Board. Deleting the board also deletes its notification settings.',
               existing_nullable=False)
    op.alter_column('board_notification_settings', 'user_id',
               existing_type=sa.UUID(),
               comment='Deleting the user also deletes their notification settings.',
               existing_nullable=False)
    op.alter_column('board_notification_settings', 'notify_hour',
               existing_type=sa.SMALLINT(),
               comment="Hour of day (0-23) at which notifications are sent, in this user's own timezone.",
               existing_comment="Hour of day (0-23) at which notifications are sent, in each recipient's own timezone.",
               existing_nullable=False,
               existing_server_default=sa.text("'9'::smallint"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('board_notification_settings', 'notify_hour',
               existing_type=sa.SMALLINT(),
               comment="Hour of day (0-23) at which notifications are sent, in each recipient's own timezone.",
               existing_comment="Hour of day (0-23) at which notifications are sent, in this user's own timezone.",
               existing_nullable=False,
               existing_server_default=sa.text("'9'::smallint"))
    op.alter_column('board_notification_settings', 'user_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Deleting the user also deletes their notification settings.',
               existing_nullable=False)
    op.alter_column('board_notification_settings', 'board_id',
               existing_type=sa.UUID(),
               comment='One-to-one with Board. Deleting the board also deletes its notification settings.',
               existing_comment="Deleting the board also deletes every user's notification settings for it.",
               existing_nullable=False)
    op.create_foreign_key(op.f('board_notification_offsets_user_id_fkey'), 'board_notification_offsets', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
